//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace open3mod {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ExportSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ExportSettings defaultInstance = ((ExportSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ExportSettings())));
        
        public static ExportSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("textures")]
        public string CopyTexturesToFolder_Target {
            get {
                return ((string)(this["CopyTexturesToFolder_Target"]));
            }
            set {
                this["CopyTexturesToFolder_Target"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseRelativeTexturePaths {
            get {
                return ((bool)(this["UseRelativeTexturePaths"]));
            }
            set {
                this["UseRelativeTexturePaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncludeSceneHierarchy {
            get {
                return ((bool)(this["IncludeSceneHierarchy"]));
            }
            set {
                this["IncludeSceneHierarchy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncludeAnimations {
            get {
                return ((bool)(this["IncludeAnimations"]));
            }
            set {
                this["IncludeAnimations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputPath {
            get {
                return ((string)(this["OutputPath"]));
            }
            set {
                this["OutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpenExportedFileInViewer {
            get {
                return ((bool)(this["OpenExportedFileInViewer"]));
            }
            set {
                this["OpenExportedFileInViewer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopyTexturesToFolder {
            get {
                return ((bool)(this["CopyTexturesToFolder"]));
            }
            set {
                this["CopyTexturesToFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ExportFormatIndex {
            get {
                return ((int)(this["ExportFormatIndex"]));
            }
            set {
                this["ExportFormatIndex"] = value;
            }
        }
    }
}
